### ISSUE TITLE
bpf_load.h doesn't existing in Linux above 5.11?

### ISSUE THREAD

**Issue by ThomsonTan** [bpftools/linux-observability-with-bpf#71]
Is there any alternative of this? Or is it recommended to copy the old one back?

**Comment by fntlnz** [comment]
Hey Tom, thanks for asking here.

I'm thinking how to approach this problem since many things changed in newer kernels.

In the meanwhile you can either copy an old one (it should just work) or alternatively use the following two functions from libbpf


- [bpf_object__open_file](https://github.com/libbpf/libbpf/blob/be89b28f96be426e30a2b0c5312d13b30ee518c7/src/libbpf.h#L166)
- [bpf_object__load](https://github.com/libbpf/libbpf/blob/be89b28f96be426e30a2b0c5312d13b30ee518c7/src/libbpf.h#L216)
